# Generated by Django 2.0.7 on 2018-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Title')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO Keywords')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO Description')),
                ('sorting', models.IntegerField(null=True, verbose_name='Сортировка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Title')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO Keywords')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO Description')),
                ('sorting', models.IntegerField(null=True, verbose_name='Сортировка')),
                ('text', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('category', models.ManyToManyField(to='goods.Category', verbose_name='Категории')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
