# Generated by Django 2.0.7 on 2018-07-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='category',
            name='sorting',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sorting',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
    ]
